### ISSUE TITLE
Remove prefix in generated resolvers file?

### ISSUE THREAD

**Issue by AlecRobertson** [eddeee888/graphql-code-generator-plugins#227]
The resolvers fill imports the queries and mutations with aliases

<img width="544" alt="Screenshot 2024-01-30 at 17 21 12" src="https://github.com/eddeee888/graphql-code-generator-plugins/assets/4457688/71b22a85-f2c0-4c9f-9ff5-f08328f0c645">

but this seems redundant as they just get assigned with the original names again:

<img width="459" alt="Screenshot 2024-01-30 at 17 21 27" src="https://github.com/eddeee888/graphql-code-generator-plugins/assets/4457688/10538bb7-ea53-4408-9299-ea81ff9de09b">

Can this feature be customised or removed?

**Comment by eddeee888** [comment]
Hi @alecrobertson1 , 

Unfortunately, we to alias resolvers with its "location" (in this case `Query_*`) so it's uniquely named in the file. Otherwise, there could be a rare scenario where a query and a mutation may have the same name e.g.

```ts
extend type Query {
  book(id: ID!): BookPayload!
}
extend type Mutation {
  book(id: ID!): BookPayload!
}
``` 

This does not happen in every GraphQL schema. But the current implementation avoids it in the simplest way possible, making the codegen implementation easy to manage. 🙂

---

Is it causing issues in your codebase or is it just a stylistic concern?
