### ISSUE TITLE
Nested interface results in error

### ISSUE THREAD

**Issue by Vishwaas** [eddeee888/graphql-code-generator-plugins#294]
**Describe the bug**
Lets say the schema had something like below:
```
interface INode {
 id: ID!
}

type User implements INode {
  name: string
  age: number
  location: Location
}
```

now I wanted to split it up as below:

```
interface INode {
 id: ID!
}

interface UserIFields implements INode {
  id: ID!
  name: string
  age: number
}

type User implements UserIFields {
  location: Location
}
```

This results in an unexpected types.generated.ts being generated.
UserIFields ends up as 
```
type UserIfields = {
name, age
}
```
and not
```
type UserIFields = INode & {
 name, age
}
```
Eg:

**To Reproduce**
_Steps to reproduce the behavior:_
_1.Setup a schema as above
2. trying implementing a node field
Eg:
```
Query Main{
  node(id: ID!): INode,
user: User
}
```

**Expected behavior**
```
type UserIFields = INode & {
 name, age
}
```

**Versions**
- OS: MacOS
- Package name and version: "@eddeee888/gcg-typescript-resolver-files": "^0.9.2",

**Comment by Vishwaas** [comment]
One more observation.

With the below interfaces: 
```
interface INode {
 id: ID!
}

interface UserIFields implements INode {
  id: ID!
  name: string
  age: number
}
```

The below does not work
```
type User implements UserIFields {
  location: Location
}
```

but the below works:
```
type User implements UserIFields & INode {
  location: Location
}
```

**Comment by eddeee888** [comment]
Hi @Vishwaas , 
Interfaces cannot implement other interfaces in a nested way you describe ([Related SO answer](https://stackoverflow.com/questions/57888591/interface-extends-multiple-interfaces-in-graphql-schema))

However, you can implement multiple interfaces with a type ([Related SO answer](https://stackoverflow.com/questions/45227332/is-it-possible-to-implement-multiple-interfaces-in-graphql))

```
interface INode {
 id: ID!
}

interface UserIFields {
  name: String
  age: Int
}

type User implements INode & UserIFields {
  id: ID!
  name: String
  age: Int
}
```

**Comment by Vishwaas** [comment]
If you look at the answer, it appears the latest graphql spec allows interfaces implementing other interfaces right?

**Comment by eddeee888** [comment]
Hi @Vishwaas 👋 
You are right, it is allowed as of the latest GraphQL version.

I'm unable to see the issue you are reporting after running it through a CodeSandbox though. Here's the schema I had to update:

```graphql
type Query {
    node(id: ID!): INode
}

interface INode {
 id: ID!
}

interface UserIFields implements INode {
  id: ID!
  name: String # Note: Updated from `string` to `String` from the issue
  age: Int # Note: Updated from `number` to `Int` from the issue
}

type User implements INode & UserIFields { # Note: Added INode here because both interfaces need to be here, otherwise it schema validation fails
  # All the fields in the interfaces needed to be here, otherwise schema validation fails
  id: ID!
  name: String
  age: Int
}

```

And here's the generated types:

<img width="532" alt="Screenshot 2024-06-16 at 9 51 59 pm" src="https://github.com/eddeee888/graphql-code-generator-plugins/assets/33769523/e5402f36-412f-4483-806a-6433a2156708">

Note that the generated interface type `UserIFields` does not add its implementing type (`INode`) since all the fields are already generated.

You can check out this [CodeSandbox](https://codesandbox.io/p/devbox/musing-leakey-2r3nl8?file=%2Fschema.graphql%3A7%2C2&workspaceId=209b5f54-0e58-4f6d-81ba-bbbe64963532&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxd7u9lq00063b8742mdzqv5%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxd7u9lq00023b87dc5h4ny1%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxd7u9lq00043b87dev1bwb0%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxd7u9lq00053b87eyw8784v%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxd7u9lq00023b87dc5h4ny1%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxd7u9lq00013b87sk8wrtjf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clxhgbv7d00153b84j80gv2fn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fcodegen.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clxhhbm0e00023b8511gwsx34%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A12%252C%2522startColumn%2522%253A44%252C%2522endLineNumber%2522%253A12%252C%2522endColumn%2522%253A44%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clxhhcvmy00023b85v7pybxdz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A7%252C%2522startColumn%2522%253A2%252C%2522endLineNumber%2522%253A7%252C%2522endColumn%2522%253A2%257D%255D%252C%2522filepath%2522%253A%2522%252Fschema.graphql%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clxd7u9lq00023b87dc5h4ny1%2522%252C%2522activeTabId%2522%253A%2522clxhhcvmy00023b85v7pybxdz%2522%257D%252C%2522clxd7u9lq00053b87eyw8784v%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clxd7u9lq00053b87eyw8784v%2522%257D%252C%2522clxd7u9lq00043b87dev1bwb0%2522%253A%257B%2522id%2522%253A%2522clxd7u9lq00043b87dev1bwb0%2522%252C%2522activeTabId%2522%253A%2522clxhhj7vv008e3b85ub6p3bma%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522codegen%2522%252C%2522id%2522%253A%2522clxhhj7vv008e3b85ub6p3bma%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) to have a play.

**Comment by eddeee888** [comment]
Closing this since it seems to work fine in tests. Please let me know if it's still an issue and I'll re-open
